'use strict';

// The weekly report content, ported from the original static report.
// Edit here (then `npm run db:seed`) or use the CRUD API once deployed.

const statuses = [
  { key: 'done', label: 'مكتمل', position: 1 },
  { key: 'progress', label: 'قيد التنفيذ', position: 2 },
  { key: 'approval', label: 'بانتظار اعتماد', position: 3 },
  { key: 'review', label: 'سيتم العرض', position: 4 },
  { key: 'inputs', label: 'بانتظار مدخلات', position: 5 },
];

const sections = [
  { id: 'strategic', position: 1, icon: 'target', title: 'المشاريع الاستراتيجية', sub: 'التحول إلى الذكاء الاصطناعي ونظم الأداء' },
  { id: 'mocasmart', position: 2, icon: 'squares-four', title: 'MOCAsmart', sub: 'خدمات ذاتية للموظفين' },
  { id: 'ops', position: 3, icon: 'gear-six', title: 'الأنظمة التشغيلية', sub: 'الخدمات المركزية' },
  { id: 'culture', position: 4, icon: 'confetti', title: 'البيئة المؤسسية', sub: 'مبادرات شهر يونيو 2026' },
  { id: 'crm', position: 5, icon: 'chart-bar', title: 'علاقات المتعاملين', sub: 'استبيانات وتسجيل الموردين' },
];

const projects = [
  // ── 1. STRATEGIC ──
  { id: 'gov-ai', section: 'strategic', status: 'progress',
    title: 'توفير البيانات للقيادة عبر منصة GOV AI',
    update: 'تم تسليم كل المتطلبات وإجراء الاختبارات، ومشاركة الملاحظات مع الأخ صقر بن غالب.',
    next: 'معالجة الملاحظات الواردة من الاختبارات.',
    detailText: 'تم تسليم كامل المتطلبات وإجراء الاختبارات من قبل الأخ علي ورئيس القطاع، وتمت مشاركة الملاحظات مع الأخ صقر بن غالب لاستكمالها.' },
  { id: 'internal-transform', section: 'strategic', status: 'inputs', priority: true,
    title: 'التحول الذكي للعمليات الداخلية',
    update: 'تم تذكير جميع الفرق لاستكمال البيانات المتبقية؛ 6 فرق أنجزت و4 لم ترسل بعد.',
    next: 'استلام مدخلات الفرق المتبقية وإغلاق المتطلبات.',
    teamGroups: [
      { caption: 'فرق أنجزت / حدّثت بياناتها', rows: [
        { name: 'المالية', note: 'تزويد المدخلات اليوم', state: 'ok' },
        { name: 'البروتوكول', note: 'أكمل — بانتظار اعتماد عبدالله علي', state: 'pend' },
        { name: 'المحتوى', note: 'مريم شاركت القائمة المحدّثة', state: 'ok' },
        { name: 'الإعلام', note: 'لا تحديثات إضافية', state: 'ok' },
        { name: 'الموارد البشرية', note: 'مكتمل — بانتظار مجلد النماذج', state: 'pend' },
        { name: 'الفعاليات والتصوير', note: 'حُدّثت — بانتظار الملفات فقط', state: 'pend' },
      ] },
      { caption: 'فرق وإدارات متبقية', rows: [
        { name: 'الأمن السيبراني', note: 'جارٍ العمل', state: 'pend' },
        { name: 'تقنية المعلومات', note: 'لا تحديثات', state: 'none' },
        { name: 'الشؤون القانونية', note: 'لم يصل رد', state: 'none' },
        { name: 'إدارة المشاريع', note: 'المشاركة الاثنين', state: 'pend' },
        { name: 'التحول الرقمي (TX)', note: 'إغلاق المتطلبات اليوم', state: 'pend' },
        { name: 'المشتريات', note: 'لم يصل رد', state: 'none' },
      ] },
    ] },
  { id: 'corporate-ai', section: 'strategic', status: 'approval', priority: true, requiresApproval: true,
    title: 'تحويل الخدمات المؤسسية إلى الذكاء الاصطناعي',
    update: 'مشاركة الخطة التنفيذية للموافقة، وإرسال ملف حالات الاستخدام للمورد لتدريب الذكاء الاصطناعي.',
    next: 'البدء في تدريب الذكاء الاصطناعي على سيناريوهات المستخدمين.',
    launch: 'عرض النموذج 18 يونيو',
    detailText: 'تمت مشاركة الخطة التنفيذية مع الأخ علي عيسى للموافقة. أُعدّ وأُرسل ملف حالات الاستخدام للمورد، واكتمل جزء كبير من الخدمات الأولية، على أن يُعرض نموذج الذكاء الاصطناعي بتاريخ 18 يونيو.' },
  { id: 'tms', section: 'strategic', status: 'progress', priority: true,
    title: 'تطوير نظام إدارة الأداء (TMS)',
    update: 'تمت مراجعة تعديلات المورد على الـ Wireframes تمهيداً للعرض على الأخ علي.',
    next: 'العرض على الأخ علي للانتقال إلى مرحلة التصميم.',
    launch: 'الاستكمال المتوقع: نوفمبر 2026',
    detailText: 'راجع الفريق التعديلات التي أجراها المورد على الـ Wireframes، وسيُعرض على الأخ علي للمضي قدماً في مرحلة التصميم. الموعد المتوقع لاستكمال المشروع نوفمبر 2026.' },

  // ── 2. MOCASMART ──
  { id: 'pm-support', section: 'mocasmart', status: 'progress',
    title: 'خدمات دعم إدارة المشاريع',
    update: 'الخدمة قيد التصميم ضمن منصة MOCAsmart.',
    next: 'استكمال التصميم تمهيداً للعرض.' },
  { id: 'eight-services', section: 'mocasmart', status: 'review', priority: true,
    title: '8 خدمات جاهزة لاعتماد رئيس القطاع',
    update: 'تصاميم جاهزة سيتم عرضها على رئيس القطاع للاعتماد خلال الأسبوع القادم.',
    next: 'العرض والاعتماد ثم الانتقال للتطوير.',
    services: [
      { icon: 'car', label: 'طلب موقف سيارة' },
      { icon: 'identification-card', label: 'بطاقة دخول (Access Card)' },
      { icon: 'camera', label: 'طلب مصوّرين' },
      { icon: 'envelope-simple', label: 'بريد إلكتروني جماعي' },
      { icon: 'medal', label: 'مزايا الموظف والترقيات' },
      { icon: 'seal-check', label: 'إقرار الموظفين' },
      { icon: 'airplane-tilt', label: 'الإيفاد والمهام الرسمية' },
      { icon: 'house-line', label: 'تحسين العمل عن بُعد' },
    ] },

  // ── 3. OPERATIONS ──
  { id: 'ifad', section: 'ops', status: 'approval', requiresApproval: true,
    title: 'نظام الإيفاد عبر MOCAsmart',
    update: 'التصميم معتمد من فريق المشتريات واكتملت النسخة العربية وشورِكت للمراجعة.',
    next: 'إعداد نطاق العمل ثم تحديد موعد الإطلاق.',
    launch: 'الإطلاق: بعد إعداد نطاق العمل',
    detailText: 'تم التواصل مع الأخت موزة المرزوقي لتنسيق اجتماع عرض مع رئيس القطاع. اعتمد فريق المشتريات التصميم، وبانتظار مشاركة نطاق العمل. اكتمل تصميم النسخة العربية وشورِك للمراجعة من فريق المشتريات.' },
  { id: 'pm-tracking', section: 'ops', status: 'progress',
    title: 'نظام إدارة ومتابعة المشاريع لرئيس القطاع',
    update: 'اعتُمدت المتطلبات وشورِك الـ SOW مع المورد بخصوص التكلفة.',
    next: 'البدء في مرحلة التصميم.',
    launch: 'الإطلاق: بعد خطة عمل المورد' },
  { id: 'vendor-dashboard', section: 'ops', status: 'done',
    title: 'لوحة تحكم إدارة الموردين',
    update: 'تم الانتهاء من المشروع بالكامل.',
    next: 'العرض على رئيس القطاع.' },
  { id: 'ai-radar', section: 'ops', status: 'progress',
    title: 'رادار الذكاء الاصطناعي',
    update: 'تصميم موقع إلكتروني باستخدام Claude AI لعرض أبرز مستجدات وأدوات الذكاء الاصطناعي.',
    next: 'تحديث المحتوى أسبوعياً ومشاركة الرابط مع رئيس القطاع.' },
  { id: 'secondment', section: 'ops', status: 'review',
    title: 'نظام الانتداب والتكليف',
    update: 'أُعدّ التصميم الأولي باستخدام Claude AI.',
    next: 'العرض على فريق الموارد البشرية لمراجعة المدخلات والملاحظات.' },
  { id: 'contract-renewal', section: 'ops', status: 'review',
    title: 'تجديد عقود الموظفين',
    update: 'النظام جاهز للإطلاق، وجارٍ تنسيق اجتماع عرض الدليل والنظام.',
    next: 'عرض النظام على رئيسة القطاع — بتنسيق موزة المرزوقي.' },
  { id: 'events-now', section: 'ops', status: 'progress',
    title: 'منصة الفعاليات (Events Now 2.0)',
    update: 'اكتمل التصميم وفق متطلبات فريق الفعاليات وعُرض عليهم.',
    next: 'إجراء بعض التعديلات المطلوبة.' },
  { id: 'ems-photo', section: 'ops', status: 'progress',
    title: 'منصة الفعاليات (EMS — التصوير الفوتوغرافي والفيديو)',
    update: 'العمل جارٍ على تصميم الواجهة الخلفية لخدمة طلب المصوّرين.',
    next: 'استكمال تصميم الواجهة الخلفية على Events Now.' },
  { id: 'attendance', section: 'ops', status: 'done', priority: true,
    title: 'نظام الحضور والانصراف (خدمات البانتري)',
    update: 'اكتمل المشروع ووافق متجر التطبيقات عليه، وهو قيد مراجعة فريق الشبكات.',
    next: 'الإطلاق ضمن نطاق شبكة الوزارة.',
    launch: 'الإطلاق المتوقع: 8 يونيو', launchSoon: true },

  // ── 4. CULTURE ──
  { id: 'yahala', section: 'culture', status: 'done',
    title: 'مبادرة «ياهلا الجديد»',
    update: 'اكتمل المشروع، والاستمرار مع شركة Entertainer مع استقبال عروض إضافية.',
    next: 'مراجعة عروض Entertainer وفيصل ورياض.' },
  { id: 'khamis', section: 'culture', status: 'progress',
    title: 'مبادرة «الخميس الونيس»',
    update: 'اعتُمد جدول شهر يونيو من رئيس القطاع.',
    next: 'تنفيذ فعالية «ميني ماتشا».',
    launch: 'الخميس 8 يونيو', launchSoon: true },
  { id: 'promotions', section: 'culture', status: 'approval', priority: true, requiresApproval: true,
    title: 'مبادرة مكافأة الحاصلين على الترقيات',
    update: 'المبادرة جاهزة وبانتظار اعتماد رئيس القطاع للإعلان.',
    next: 'الاعتماد للمضي قدماً في التنفيذ.' },
  { id: 'hajj', section: 'culture', status: 'inputs',
    title: 'مبادرة الحج',
    update: 'بانتظار قائمة الموظفين من الأخ محمد جمعة.',
    next: 'طلب الأعلام والحلويات بعد استلام القائمة.' },
  { id: 'bags', section: 'culture', status: 'approval', priority: true, requiresApproval: true,
    title: 'الحقائب المخصصة للموظفات',
    update: 'تصميم مجموعة حقائب تحمل أسماء الموظفات، وجارٍ إعداد نموذج أولي.',
    next: 'الحصول على الموافقة النهائية من رئيس القطاع.' },

  // ── 5. CRM ──
  { id: 'supplier-survey', section: 'crm', status: 'progress',
    title: 'استبيان رضا الموردين',
    update: 'أُعدّت التحليلات بناءً على النتائج وعُرضت على رئيس القطاع.',
    next: 'تنفيذ ملاحظات رئيس القطاع.',
    detailText: 'بتوجيه من رئيس القطاع وبالتنسيق مع الأخت مريم البلوشي والأخ خليفة الحبسي، أُعدّت التحليلات بناءً على النتائج وعُرضت، ويجري حالياً تنفيذ الملاحظات.',
    documentName: 'استبيان رضا الموردين 2025.pdf',
    documentUrl: '/docs/supplier-satisfaction-survey-2025.pdf' },
  { id: 'employee-survey', section: 'crm', status: 'progress',
    title: 'استبيان رضا الموظفين',
    update: 'بلغت نسبة الاستجابة 46% بمشاركة 105 موظفين.',
    next: 'تمديد فترة الاستبيان حتى 13 يونيو لرفع نسبة المشاركة.',
    progress: 46,
    launch: 'انتهاء الاستبيان: 13 يونيو', launchSoon: true },
  { id: 'supplier-reg', section: 'crm', status: 'review',
    title: 'تقرير تسجيل الموردين — يونيو',
    update: 'حالة طلبات تسجيل الموردين لشهر يونيو.',
    stats: [
      { n: '3', l: 'إجمالي الطلبات' },
      { n: '0', l: 'مكتملة' },
      { n: '8', l: 'قيد التسجيل' },
      { n: '4', l: 'بانتظار المورد' },
      { n: '1', l: 'بانتظار الموارد البشرية' },
      { n: '2', l: 'اعتماد على النظام', amber: true },
      { n: '1', l: 'اعتماد على النموذج', amber: true },
    ] },
];

module.exports = { statuses, sections, projects };
